version: '3.8'

services:

  api-ts:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./v1/src:/home/node/app/src
    container_name: api
    expose:
      - '3001'
    ports:
      - '3001:3001'
    env_file:
      - .env
    networks:
      - camel-net
    command: npm run dev

networks:
  camel-net:
    external: true
